export const LoaderIcon = (props: React.SVGProps<SVGSVGElement>) => {
  return (
    <svg
      height="16"
      width="16"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
      {...props}
    >
      <g transform="rotate(0 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="-0.5208333333333333s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(60 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="-0.41666666666666663s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(120 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="-0.31249999999999994s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(180 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="-0.20833333333333331s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(240 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="-0.10416666666666666s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(300 50 50)">
        <rect
          x="44"
          y="0.5"
          rx="6"
          ry="6.29"
          width="12"
          height="37"
          fill="currentColor"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="0.625s"
            begin="0s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
    </svg>
  );
};
