export { Avatars } from './Avatars';
export { Cta } from './Cta';
export { default as DemoResumeDesktop } from './demo-resume-desktop';
export { DemoResume } from './demo-resume';
export { Demo } from './Demo';
export { Footer } from './footer';
export { Hero } from './Hero';
export { DATA } from './resume';
export { UniqueLink } from './unique-link';
export { VideoDialog } from './video-dialog';
